### ISSUE TITLE
CPU time limit error when transferring large number of contacts

### ISSUE THREAD

**Issue by mazz44** [force2b/MassTransferContacts#4]
When transferring somewhere around 500 contacts there is a time out error. Here is the error message.

---

Apex CPU time limit exceeded
Error is in expression '{!doTransfer}' in component apex:commandButton in page f2b:masstransfercontacts: (f2b)
An unexpected error has occurred. Your solution provider has been notified. (f2b)

---

Attached is the debug log that shows the CPU warnings.

[apex-07Ld000003OoNEfEAN.log.txt](https://github.com/force2b/MassTransferContacts/files/443417/apex-07Ld000003OoNEfEAN.log.txt)

**Comment by force2b** [comment]
Thank you for the log. Very helpful. 

The transfer app is pretty light weight, so when looking at a timeout/cpu issue, the root is always in triggers or process builder(s) on the Contact or Account objects. The NPSP app does have triggers, and a lot of overhead in general, but I've also used this app successfully in NPSP3 orgs. I'm not sure on the "cbit" app, but since it's showing up in the log, there must be a cbit trigger being executed somewhere along the path. Processes are harder to nail down, but I've seen larger processes cause this error, particularly ones that do a lot field updates. I didn't see any references to processes, in there, but maybe they weren't included. I suppose there could be other custom code involved too. 

Your best bet is to reduce the number of records you transfer at one time (using the filters to reduce the results).  More than likely it will work if you transfer 200 or 300 at once versus 500+. There have been posts on The HUB suggesting really small batch sizes when importing into an NPSP org, but I don't see as being necessary for ownership transfers.

Long term though, it may be that I'll either need to automatically reduce the result set size when NPSP is installed and/or give the user an option to set the limit right in the UI.

Let me know what you find, especially if you still can't get it to work with a smaller number of Contacts.

**Comment by mazz44** [comment]
The cbit is for ClearBit https://clearbit.com/salesforce.
I do know if there is about 250 records it does work. The contact transfer is used to move records when someone leaves so it takes multiple tries to get the correct amount that will not cause it to error out. The only good option for this situation was to use a created date filter. But sometimes a large batch of contacts is added in a month so that complicates the query.
It would be best if there was a limit of rows returned I could set so it would be quicker to search and repeat the transfer. That is what I see in the Mass Transfer tool in SF and the previous iteration of this tool.
Thanks for the transfer tool. I like the new interface.

**Comment by force2b** [comment]
I'm glad you like the new UI. I'll also add a task for me to build in a batch size option into the UI to better handle these scenarios.
